import { useEffect, useRef } from 'react'
import { HiOutlineExclamationCircle } from 'react-icons/hi'

import { useChatStore } from '@/stores/chat'

import { LimitedError } from './Errors/LimitedError'
import { NetworkError } from './Errors/NetworkError'
import { MessageList } from './MessageList'

export function Content() {
  const { limitedError, networkError } = useChatStore()
  const contentRef = useRef<null | HTMLDivElement>(null)

  useEffect(() => {
    contentRef.current?.addEventListener('scroll', handleScroll)

    return () => contentRef.current?.removeEventListener('scroll', handleScroll)
  }, [])

  function handleScroll(e: any) {
    if (e.target.scrollTop !== 0) {
      return
    }
  }

  return (
    <div
      style={{
        background:
          'linear-gradient(0deg, #D3DAED 0%, #D3DAED 100%), rgba(0, 0, 0, 0.20)',
      }}
      className="overflow-auto px-16px flex h-full w-full flex-col overflow-auto rounded-xl"
    >
      <div ref={contentRef} className="h-full min-h-0 w-full flex-1">
        <div className="py-7px px-16px rounded-8px mt-24px bg-#E0E5F2 flex text-gray-400">
          <HiOutlineExclamationCircle className="mr-1 h-6 w-6" />
          <span className="text-14px">
            This AI is generated by users, not affiliated with any person or
            brand.
          </span>
        </div>
        <MessageList />

        {limitedError && <LimitedError />}
        {networkError && <NetworkError />}
      </div>
      {/* <div className="h-110px w-full">
        <Toolbar />
      </div> */}
    </div>
  )
}
